<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>Mobius</AssemblyName><Product>Möbius</Product><Title>Möbius</Title><AssemblyTitle>Möbius</AssemblyTitle>
    <Version>0.8.3</Version>
    <ApplicationIcon>Assets\Mobius.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><EmbeddedResource Include="Assets\Mobius.ico" LogicalName="Mobius.Icon" /></ItemGroup>
  <ItemGroup><EmbeddedResource Include="Assets\Mobius.png" LogicalName="Mobius.Logo" /></ItemGroup>
</Project>




